[supabase]
url = "https://nkkoojvsiucvymfxvmse.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ra29vanZzaXVjdnltZnh2bXNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3NzQ4NzQsImV4cCI6MjA3NDM1MDg3NH0.0pmUnfleuOptvVCPFiWOX9vVi9_yriON6-ezyL4KPQ8"